### ISSUE TITLE
Error - Unable to Login

### ISSUE THREAD

**Issue by sp00ky** [emonney/QuickApp#44]
I'm getting the following exception when I login.  The OpenIddictAuthorizations only has the colums Id, ApplicationId, Scope, Status, and Subject.  Could there have been some version changes in OpenIddict? 

      Activated	Event	Time	Duration	Thread
	Program Output: Microsoft.EntityFrameworkCore.Database.Command:Error: Failed executing DbCommand (90ms) [Parameters=[@p0='?' (Size = 450), @p1='?' (Size = 450), @p2='?' (Size = 4000), @p3='?' (Size = 4000), @p4='?' (Size = 4000), @p5='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [OpenIddictAuthorizations] ([Id], [ApplicationId], [Scopes], [Status], [Subject], [Type])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5);
SELECT [Timestamp]
FROM [OpenIddictAuthorizations]
WHERE @@ROWCOUNT = 1 AND [Id] = @p0;

System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Scopes'.
Invalid column name 'Type'.
Invalid column name 'Timestamp'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
ClientConnectionId:4563d889-c9bd-4b61-a2e2-dcec43c20bd6
Error Number:207,State:1,Class:16	63.55s

**Comment by CybrZr00** [comment]
Same problems here, and some other weird things happening when I try to publish.  Whilst in debug the app starts, when trying to publish via cli I get errors: 

>  error CS1061: 'AuthenticationBuilder' does not contain a definition for 'AddOAuthValidation' and no extension method 'AddOAuthValidation' accepting a first argument of type 'AuthenticationBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by rafsanulhasan** [comment]
Install AspNet.Security.OAth.Valivation 2.0.0-rc1-0286 (final) NuGet Package to resolve this issue @CybrZr00

**Comment by CybrZr00** [comment]
thanks, seems I had 2 entries in my csproj removing the ref to the old version has fixed it.

**Comment by garyhoff1** [comment]
I'm also getting the error Invalid column name 'Scopes', 'Type', 'Timestamp' on table OpenIddictAuthorizations.
I uninstalled and installed Install AspNet.Security.OAth.Valivation 2.0.0-rc1-0286 (final), 
Changed DAL.cspfoj:
<pre>PackageReference Include="OpenIddict" Version="2.0.0-rc1-final"
PackageReference Include="OpenIddict.EntityFrameworkCore" Version="2.0.0-rc1-final"
</pre>
Still get error.
<pre>Code in Migrations\20170913022214_Initial.cs:
            migrationBuilder.CreateTable(
                name: "OpenIddictAuthorizations",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ApplicationId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    Scope = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Status = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Subject = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },</pre>
Does this need to be changed to include the new columns?

**Comment by speddi** [comment]
I am trying to host the application in IIS and I getting the following error in the console when I try to login. 

(I removed all the html details in the error message).

Requested URL http://localhost:8080/connect/token Physical Path C:\\inetpub\\wwwroot\\connect\\token Logon Method Anonymous Logon User Anonymous More Information:  This error means that the file or directory does not exist on the server. Create the file or directory and try the request again

How do I fix it? Thank you

**Comment by CybrZr00** [comment]
@speddi Looks like an IIS setup issue.  This isn't really the place for help with that.

**Comment by CybrZr00** [comment]
@garyhoff1 I was thinking that, I tried adding the columns manually, but couldn't get the Timestamp column to work, I only tried DateTime and timestamp types and gave up.

**Comment by speddi** [comment]
@CybrZr00 This might be an IIS issue but it will be a problem anytime we create an application in IIS and deploy the code to that application. Does this not support deploying the app to a application under Default Web Site like 'Default Web Site/MyApp'

**Comment by CybrZr00** [comment]
This issue is for what spooky has pointed out in the OP. Maybe open a new issue?

**Comment by speddi** [comment]
@CybrZr00 got it. I opened a new ticket. Thank you.

**Comment by CybrZr00** [comment]
As a horrible hack, I added the missing columns manually (changed scope to scopes) I set all the data types to NVARCHAR(MAX) also added Timestamp to OpeniddictTokens also as NVARCHAR. 

I have noticed that entries into the tables are missing an ApplicationId and Timestamp so despite this hack appearing to work, there is data missing.

**Comment by garyhoff1** [comment]
To fix the  OpenIddict database errors I changed the following in Migrations 20170913022214_Initial.cs.
It fixed the issue, I can now login.  Not sure if there are any other attributes (nullable or not) that I might have wrong.
<pre>
                name: "OpenIddictAuthorizations",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ApplicationId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    Scopes = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Status = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Subject = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Type = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Timestamp = table.Column<string>(type: "timestamp", nullable: false),
                },

                name: "OpenIddictTokens",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ApplicationId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    AuthorizationId = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    Ciphertext = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    End = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    Hash = table.Column<string>(type: "nvarchar(450)", nullable: true),
                    Start = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    Status = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Subject = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Type = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CreationDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ExpirationDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Timestamp = table.Column<string>(type: "timestamp", nullable: false)
                },
</pre>

**Comment by HansHammel** [comment]
confirmed at OpenIddictAuthorizations it has to be 

> Scope**s** = table.Column(type: "nvarchar(max)", nullable: true),

the s was missin

**Comment by NotEvolved** [comment]
I'm sure this is an embarrassingly newbie question...but I made the changes to the migration, but they don't seem to be having any effect.  Do I have to do something to drop the tables for the migration to recreate them? Any insight would be greatly appreciated.

**Comment by garyhoff1** [comment]
I went into Microsoft SQL Server Management Studio and deleted the entire database, and added back a new empty database with the same name (using right mouse click options). That should do it.

**Comment by Svakinn** [comment]
There is currently open pull request from HansHammel that should resolve this issue

**Comment by nicocomumu** [comment]
The is a missunderstoor on the origin of your problem. I think if you have this error it's because you have updated the version of OpenIddict, and this library has a different database schema that the oldest version included in QuickApp. To sove this, you have to create a new EF migration and absolutly not change the existing migration!
Open NuGet Package Manager Console and enter 
   Add-Migration "OpenIddictV2"
This will generate a new migration step, and the next execution will use it to update your database.
"OpenIddictV2" is just the name of yout migration. Each time you change your EF models, you should ask for a new corresponding migration

**Comment by emonney** [comment]
It appears you're using a newer/different version of OpenIddict that has different database schema.
Like @nicocomumu  suggested, you'll need to apply a new EF migrations to update the database properly.
Manually updating the db is not the right way.

Closing this thread. If this is still an issue please reopen.

**Comment by KhaledSMQ** [comment]
I think the problem related to 
https://github.com/openiddict/openiddict-core/pull/504/commits/37e24a5e76e46addf2cc103e47bf119e4c2c87fb
still not solved
