### ISSUE TITLE
App doesn't publish.

### ISSUE THREAD

**Issue by Sami-L** [emonney/QuickApp#75]
Publishing with Visual Studio 2017 give the following error:

Severity Code Description Project File Line Suppression State
**Error: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2**.	
QuickApp C:\Projects\QuickApp\src\QuickApp\QuickApp.csproj 62

This is related to AOT compilation of Angular, and I read some explanations [here](https://github.com/angular/angular/issues/11422).

> For a given component all its members (methods, properties) accessed by its template must be public in the ahead-of-time compilation scenario. This is due to the fact that a template is turned into a TS class. A generated class and a component are 2 separate classes now and you can't access private members cross-class.

Could someone confirm that this is the case here ?

If so where specifically apply the changes ?
  

**I am using:**
Angular version: 5.1.1           tried also with 5.1.0 (same error)
Browser: [all]
Language: [TypeScript 2.6.2]
Node (for AoT issues):
node --version = 8.9.3  (LTS)
npm --version = 5.5.1

**Comment by emonney** [comment]
This is the case for all angular apps from version 4.x and above (I don't recall the exact version).
You have a property you're referencing from the template and you need to remove the private access modifier from it.
Are you experiencing this from a vanilla installation?

Support requests are better discussed from the [support forum](http://www.ebenmonney.com/forum/?view=forum&id=14).
And github issues for bug reports.

**Comment by Sami-L** [comment]
I just tried a new vanilla installation, and this issue don't happen, so as you said I need to find the private access causing that. Thank you.

**Comment by codestellar** [comment]
@Sami-L This is indeed having issue. So, I published them separately.
Removed this code from QuickApp.csproj
`<Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    
    <Exec Command="npm install" />
    <Exec Command="node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod" />
    <Exec Command="node node_modules/webpack/bin/webpack.js --env.prod" />

    
    <ItemGroup>
      <DistFiles Include="wwwroot\dist\**; ClientApp\dist\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>`
Then run the following commands:

1. dotnet publish -c release -r win10-x64 --self-contained
1. webpack --config webpack.config.vendor.js
1. webpack
1. Copy the publish folder in bin > release > win10-x64 > publish and dist from wwwroot to the location where you want to deploy or add tasks in the deployment profile.

**Comment by Sami-L** [comment]
@codestellar thanks for the workaround,
1. dotnet publish -c release -r win10-x64 --self-contained still gives the error:
   **The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2**
2. ok
3. ok
4. There is nothing to copy from the ~\bin\release\win10-x64\publish folder

I have followed your method but after deployment got the following error:
HTTP Error 502.5 - Process Failure

**Comment by codestellar** [comment]
@Sami-L Make sure that the following module is installed on the IIS.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/aspnet-core-module?tabs=aspnetcore2x

and your app pool is using 'No managed code'

![applicationpool](https://user-images.githubusercontent.com/17561784/35205790-eb3a99e0-ff5d-11e7-86e1-a99dc08f9da7.PNG)

**Comment by codestellar** [comment]
@Sami-L Make sure that you have installed ASPNet Core module.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/aspnet-core-module?tabs=aspnetcore2x

**Comment by Sami-L** [comment]
@codestellar ASPNet Core module is already installed an d up to date.

> dotnet publish -c release -r win10-x64 --self-contained

still fails.

**Comment by Sami-L** [comment]
Figured it out, 

Visual Studio 2017 doesn't detect all TypeScript errors, thanks to [this link](https://www.ryadel.com/en/the-command-node-node_modules-webpack-bin-webpack-js-env-prod-exited-with-code-2-error-fix-angular-node/) I could find an error in code using the command 

`node node_modules/webpack/bin/webpack.js --env.prod`

fixed the error, then the project published normally.

**Comment by codestellar** [comment]
@Sami-L I would recommend using VSCode strongly specially for front end development. :) The command line gives clear errors :)

**Comment by Sami-L** [comment]
@codestellar I agree, thank you, now I have to check errors also with VSCode, since VS 2017 keeps needed for Backend tasks.
